apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: demo-wp
  labels:
    app: wordpress-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: wordpress-mysql
	