apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-web
  namespace: demo-wp
  labels:
    app: wordpress-web
spec:
  selector:
    matchLabels:
      app: wordpress-web
  template:
    metadata:
      labels:
        app: wordpress-web
    spec:
      containers:
      - image: wordpress:php8.0-apache
        name: wordpress-web
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_NAME
          value: wordpress_db
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: onlyDevelopment
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
		  