---
- name: restart nginx
  service: name=nginx state=restarted

- name: validate nginx configuration and restart nginx
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: true
  notify:
    - restart nginx

- name: restart apache2
  service: name=apache2 state=restarted

- name: validate apache2 configuration and restart apache2
  command: /usr/sbin/apachectl configtest
  changed_when: true
  notify:
    - restart apache2
