apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec: 
      template:
        spec:
          containers:
          - name: count-container
            image: debian:latest
            command: 
            - "/bin/bash"
            - "-c"
            - "apt-get update; apt-get install curl -y ; curl -s http://wttr.in/Wroclaw"
          restartPolicy: Never