apiVersion: v1
kind: Secret
metadata:
  name: secret-test
data:
  user: cm9vdA==              # "dbadmin" in base 64
  pass: ZGJwYXNzd29yZDEyMyE=  # "dbpassword123!" in base 64
stringData: # plain text data
  dbaddress: "localhost"
  dbname: "test"