apiVersion: v1
kind: Pod
metadata:
  name: secret-test
spec:
  containers:
  - name: secret-test
    image: mysql:5.7.34
    command: ["env"]
    env: # secret value as environment variable
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-test
          key: pass    
    volumeMounts: 
    - mountPath: "/root/secrets"
      name: dbsecrets
      readOnly: true
  volumes:
  - name: dbsecrets
    secret:
      secretName: secret-test