apiVersion: v1
kind: Pod
metadata:
  name: three-pods
spec:
  containers:
    - name: ubuntu
      image: ubuntu:18.04
      command: ["sleep", "inf"]
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: httpd
      image: httpd
      ports:
        - containerPort: 8080 # ERROR make_sock: could not bind to address 0.0.0.0:80