apiVersion: v1
kind: Pod
metadata:
  name: pod-multiple
spec:
  containers:
    - name: ubuntu
      image: ubuntu:18.04
      command: ["sleep", "inf"]
    - name: nginx-with-ubuntu
      image: nginx
      ports:
        - containerPort: 80