apiVersion: v1
kind: Namespace
metadata:
  name: demo-wp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: demo-wp
  labels:
    app: wordpress-mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: demo-wp
  labels:
    app: wordpress-mysql
spec:
  selector:
    matchLabels:
      app: wordpress-mysql
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
        - image: mariadb:10.5
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: onlyDevelopment
            - name: MYSQL_DATABASE
              value: wordpress_db
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: demo-wp
  labels:
    app: wordpress-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: wordpress-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: demo-wp
  labels:
    app: wordpress-web
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-web
  namespace: demo-wp
  labels:
    app: wordpress-web
spec:
  selector:
    matchLabels:
      app: wordpress-web
  template:
    metadata:
      labels:
        app: wordpress-web
    spec:
      containers:
        - image: wordpress:php8.0-apache
          name: wordpress-web
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_NAME
              value: wordpress_db
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              value: onlyDevelopment
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-web
  namespace: demo-wp
  labels:
    app: wordpress-web
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress-web
