---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Automatyczne dodawanie tagu wlasciciela do instancji EC2
Parameters:
  CreateCloudTrail:
    Description: 'Tworzy usluge CloudTrail (nadaj temu parametrowi wartosc "falsz", jesli na Twoim koncie jest juz wlaczona usluga CloudTrail).'
    Type: String
    Default: 'prawda'
    AllowedValues: ['prawda', 'falsz']
Conditions:
  HasCreateCloudTrail: !Equals [!Ref CreateCloudTrail, 'prawda']
Resources:
  TrailBucket:
    Condition: HasCreateCloudTrail
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${AWS::AccountId}'
  TrailBucketPolicy:
    Condition: HasCreateCloudTrail
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSCloudTrailAclCheck
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:GetBucketAcl'
          Resource: !Sub 'arn:aws:s3:::${TrailBucket}'
        - Sid: AWSCloudTrailWrite
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:PutObject'
          Resource: !Sub 'arn:aws:s3:::${TrailBucket}/AWSLogs/${AWS::AccountId}/*'
          Condition:
            StringEquals:
              's3:x-amz-acl': 'bucket-owner-full-control'
  Trail:
    Condition: HasCreateCloudTrail
    DependsOn: TrailBucketPolicy
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      IsLogging: true
      IsMultiRegionTrail: false
      S3BucketName: !Ref TrailBucket
  EC2OwnerTagFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: '.'
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: 'ec2:CreateTags'
          Resource: '*'
      Events:
        CloudTrail:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
              - 'AWS API Call via CloudTrail'
              source:
              - 'aws.ec2'
              detail:
                eventName:
                - 'RunInstances'
