- name: Install tools
  apt: name={{ item }} state=latest
  with_items:
    - pydf
    - tree
    - open-vm-tools
  tags: installation_tag

- name: copy hosts
  template: src=hosts.j2 dest=/etc/hosts
  tags: configuration_tag