---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS w akcji: rozdzial 6 (zapora sieciowa 4)'
Parameters:
  KeyName:
    Description: 'Nazwa pary kluczy'
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: mykey
  VPC:
    Description: 'Wybierz po prostu jedyna dostepna domyslna usluge VPC'
    Type: 'AWS::EC2::VPC::Id'
  Subnet:
    Description: 'Wybierz po prostu jedna z dostepnych podsieci'
    Type: 'AWS::EC2::Subnet::Id'
  IpForSSH:
    Description: 'Twoj publiczny adres IP, z ktorego chcesz miec dostep przez SSH'
    Type: String
    AllowedPattern: '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
    ConstraintDescription: 'Wprowadz poprawny adres IPv4'
Mappings:
  RegionMap:
    'ap-south-1':
      AMI: 'ami-2ed19c41'
    'eu-west-3':
      AMI: 'ami-c8a017b5'
    'eu-west-2':
      AMI: 'ami-e3051987'
    'eu-west-1':
      AMI: 'ami-760aaa0f'
    'ap-northeast-2':
      AMI: 'ami-fc862292'
    'ap-northeast-1':
      AMI: 'ami-2803ac4e'
    'sa-east-1':
      AMI: 'ami-1678037a'
    'ca-central-1':
      AMI: 'ami-ef3b838b'
    'ap-southeast-1':
      AMI: 'ami-dd7935be'
    'ap-southeast-2':
      AMI: 'ami-1a668878'
    'eu-central-1':
      AMI: 'ami-e28d098d'
    'us-east-1':
      AMI: 'ami-6057e21a'
    'us-east-2':
      AMI: 'ami-aa1b34cf'
    'us-west-1':
      AMI: 'ami-1a033c7a'
    'us-west-2':
      AMI: 'ami-32d8124a'
Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Naucz sie zabezpieczac instancje EC2.'
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: 'AWS w akcji: rozdzial 6 (zapora sieciowa)'
      # zezwolenie na przychodzacy ruch ICMP
      SecurityGroupIngress:
      - IpProtocol: icmp
        FromPort: '-1'
        ToPort: '-1'
        CidrIp: '0.0.0.0/0'
      # zezwolenie na przychodzacy ruch SSH
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Sub '${IpForSSH}/32'
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: 't2.micro'
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - !Ref SecurityGroup
      SubnetId: !Ref Subnet
      Tags:
      - Key: Name
        Value: 'AWS w akcji: rozdzial 6 (zapora sieciowa)'
Outputs:
  PublicName:
    Value: !Sub ${Instance.PublicDnsName}
    Description: 'Publiczna nazwa instancji EC2 (lacz sie przez SSH jako uzytkownik ec2-user)'
