---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS w akcji: rozdzial 9 (magazyn instancji)'
Parameters:
  KeyName:
    Description: 'Nazwa pary kluczy'
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: mykey
  VPC:
    Description: 'Wybierz po prostu jedyna dostepna domyslna usluge VPC'
    Type: 'AWS::EC2::VPC::Id'
  Subnet:
    Description: 'Wybierz po prostu jedna z dostepnych podsieci'
    Type: 'AWS::EC2::Subnet::Id'
Mappings:
  RegionMap:
    'ap-south-1':
      AMI: 'ami-2ed19c41'
    'eu-west-3':
      AMI: 'ami-c8a017b5'
    'eu-west-2':
      AMI: 'ami-e3051987'
    'eu-west-1':
      AMI: 'ami-760aaa0f'
    'ap-northeast-2':
      AMI: 'ami-fc862292'
    'ap-northeast-1':
      AMI: 'ami-2803ac4e'
    'sa-east-1':
      AMI: 'ami-1678037a'
    'ca-central-1':
      AMI: 'ami-ef3b838b'
    'ap-southeast-1':
      AMI: 'ami-dd7935be'
    'ap-southeast-2':
      AMI: 'ami-1a668878'
    'eu-central-1':
      AMI: 'ami-e28d098d'
    'us-east-1':
      AMI: 'ami-6057e21a'
    'us-east-2':
      AMI: 'ami-aa1b34cf'
    'us-west-1':
      AMI: 'ami-1a033c7a'
    'us-west-2':
      AMI: 'ami-32d8124a'
Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Zezwol na ruch SSH przychodzacy z kazdego miejsca'
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - CidrIp: '0.0.0.0/0'
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
      Tags:
      - Key: Name
        Value: 'AWS w akcji: rozdzial 9 (magazyn instancji)'
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: 'm3.medium'
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - !Ref SecurityGroup
      SubnetId: !Ref Subnet
      BlockDeviceMappings:
      - DeviceName: '/dev/xvda'
        Ebs:
          VolumeSize: '8'
          VolumeType: gp2
      - DeviceName: '/dev/xvdb'
        VirtualName: ephemeral0
      Tags:
      - Key: Name
        Value: 'AWS w akcji: rozdzial 9 (magazyn instancji)'
Outputs:
  PublicName:
    Value: !Sub ${EC2Instance.PublicDnsName}
    Description: 'Nazwa publiczna (lacz sie przez SSH jako uzytkownik ec2-user)'
