- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 8443
    http_welcome_msg: "Hello world!"
  roles:
    - common
    - apache2  
  
- hosts: webstack
  become: True
  roles:
    - common

- hosts: proxy
  become: yes
  roles:
    - common
    - nginx
