Vagrant.configure("2") do |config|
    servers=[
        {
            :hostname => 'ansible-control',
            :box => 'bento/ubuntu-18.04',
            :ip => '192.168.56.100',
            :ssh_port => '2200'
        },
        {
            :hostname => 'proxy',
            :box => 'bento/ubuntu-18.04',
            :ip => '192.168.56.101',
            :ssh_port => '2201'
        },
        {
            :hostname => 'webserver1',
            :box => 'bento/ubuntu-18.04',
            :ip => '192.168.56.102',
            :ssh_port => '2202'
        },
        {
            :hostname => 'webserver2',
            :box => 'bento/ubuntu-18.04',
            :ip => '192.168.56.103',
            :ssh_port => '2203'
        },
        {
            :hostname => 'db',
            :box => 'bento/ubuntu-18.04',
            :ip => '192.168.56.104',
            :ssh_port => '2204'
        },
    ]    
    servers.each do |machine|

        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            config.vm.box_download_insecure=true

            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: 'ssh'
        end
    end
end